# Generated by Django 5.2.13 on 2026-05-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cyber_attack_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flowid', models.CharField(max_length=300)),
                ('Timestamp', models.CharField(max_length=300)),
                ('SourceIP', models.CharField(max_length=300)),
                ('DestinationIP', models.CharField(max_length=300)),
                ('protocol_type', models.CharField(max_length=300)),
                ('service', models.CharField(max_length=300)),
                ('flag', models.CharField(max_length=300)),
                ('src_bytes', models.CharField(max_length=300)),
                ('dst_bytes', models.CharField(max_length=300)),
                ('Total_Fwd_Packets', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
    ]
